---
- name: PRE INSTALLATION
  include_tasks: pre-install.yml
  tags:
    - pre-install

- name: INSTALL KAFKA CONNECT PLUGINS
  include_tasks: plugins.yml
  tags:
    - plugins

- name: CONFIGURE KAFKA CONNECT
  include_tasks: configure.yml
  tags:
    - configure

- name: CONFIGURE KAFKA CONNECT SERVICE
  include_tasks: service.yml
  tags:
    - service

- name: VERIFY KAFKA CONNECT
  include_tasks: verify.yml
  tags:
    - verify
