---
- name: Deploy Schema Registry configuration
  ansible.builtin.template:
    src: schema-registry.properties.j2
    dest: "{{ schema_registry_config_dir }}/schema-registry.properties"
    owner: "{{ schema_registry_user }}"
    group: "{{ schema_registry_group }}"
    mode: "0644"
  notify:
    - Restart Schema Registry
  tags:
    - configure
